# # -*- coding: utf-8 -*-
# """tb.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1Bjmgovp5EuLDO1uaa4VQXGX0lHFMGs1C
# """

# #!wget https://www.dropbox.com/s/hetzz62kfxw8xhv/finalmodel.h5

# !wget https://www.dropbox.com/s/bh76l8fwp67hwkz/finalmodel.h5

# !wget https://www.dropbox.com/s/vznp8c6zhwam0xm/temp.zip

# """# New Section"""

# !unzip temp.zip

# !pip install pyngrok==4.1.1
# !pip install flask_ngrok

# !ngrok authtoken 2AIuN2rt9f5UvAyXvndrunLb8Uc_4cADsEaozTwLsyRxhSXV4

from flask import Flask, render_template, request
from keras.models import load_model
from keras.preprocessing import image
from flask_ngrok import run_with_ngrok
from pyngrok import ngrok
from PIL import Image
import cv2
import numpy as np
import base64
import io
import re

def func(path):
  img = image.load_img(path,target_size=(224,224))

  i=image.img_to_array(img)/255
  input_arr = np.array([i])
  input_arr.shape


  pred1=(model.predict(input_arr))
  print (pred1)
  a= 1-pred1

  if (a<pred1):
    msg = "T.B. Positive"
  else:
    msg = "T.B. Negative"

  return msg

app = Flask(__name__)
# run_with_ngrok(app)

model=load_model('finalmodel.h5')

@app.route("/")
def index():
	return(render_template("index.html"))
 

 
@app.route("/predict", methods = ['POST'])
def predict():
	if request.method == 'POST':
		img = request.files['my_image']

		img_path = "static/" + img.filename	
		img.save(img_path)
  
		p = func(img_path)

	return render_template("index.html", prediction = p, img_path = img_path)

if __name__ == "__main__":
  app.run(debug=False,host='0.0.0.0')

# ngrok.kill()